# exporter server config
server:
  address: 127.0.0.1 # address to run exporter
  port: 9123 # port to listen

# list of jmx service to scape metrics
jmx:
  - cluster: hdfs_cluster
    component: hdfs
    services:
      namenode:
        - http://nn1:9870/jmx
      datanode:
        - http://dn1:9864/jmx
        - http://dn2:9864/jmx
        - http://dn3:9864/jmx

  - cluster: yarn_cluster
    component: yarn
    services:
      resourcemanager:
        - http://rm1:9870/jmx
      nodemanager:
        - http://nm1:9864/jmx
        - http://nm2:9864/jmx
        - http://nm3:9864/jmx
