{
 "title": "HDFS Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(hadoop_hdfs_namenode_fsstate, cluster)"
    }
   },
   {
    "name": "namenode",
    "label": "namenode",
    "query": {
     "query": "label_values(hadoop_hdfs_namenode_fsstate{cluster=~\"$cluster\"}, host)"
    }
   },
   {
    "name": "datanode",
    "label": "datanode",
    "query": {
     "query": "label_values(hadoop_hdfs_datanode_rpcactivity{cluster=~\"$cluster\"}, host)"
    }
   },
   {
    "name": "journalnode",
    "label": "journalnode",
    "query": {
     "query": "label_values(hadoop_hdfs_journalnode_rpcactivity{cluster=~\"$cluster\"}, host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Capacity",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(hadoop_hdfs_namenode_fsnamesystem_capacity{cluster=~\"$cluster\", type=~\"Remaining|Used\"}) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "NameNodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(hadoop_hdfs_namenode_fsstate{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "JournalNodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(hadoop_hdfs_journalnode_threading{type=\"ThreadCount\"})"
    }
   ]
  },
  {
   "title": "Live DataNodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(hadoop_hdfs_namenode_fsnamesystem_num_datanodes{cluster=~\"$cluster\", type=\"Live\"})"
    }
   ]
  },
  {
   "title": "Dead DataNodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(hadoop_hdfs_namenode_fsnamesystem_num_datanodes{cluster=~\"$cluster\", type=\"Dead\"})"
    }
   ]
  },
  {
   "title": "DecomLive DataNodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(hadoop_hdfs_namenode_fsnamesystem_num_datanodes{cluster=~\"$cluster\", type=\"DecomLive\"})"
    }
   ]
  },
  {
   "title": "DecomDead DataNodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(hadoop_hdfs_namenode_fsnamesystem_num_datanodes{cluster=~\"$cluster\", type=\"DecomDead\"})"
    }
   ]
  },
  {
   "title": "Total Files",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(hadoop_hdfs_namenode_fsnamesystem{cluster=~\"$cluster\", type=\"FilesTotal\"})"
    }
   ]
  },
  {
   "title": "Total Blocks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(hadoop_hdfs_namenode_fsnamesystem{cluster=~\"$cluster\", type=\"BlocksTotal\"})"
    }
   ]
  },
  {
   "title": "Missing Blocks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(hadoop_hdfs_namenode_fsnamesystem_blocks{cluster=~\"$cluster\", type=\"Missing\"})"
    }
   ]
  },
  {
   "title": "Corrupt Blocks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(hadoop_hdfs_namenode_fsnamesystem_blocks{cluster=~\"$cluster\", type=\"Corrupt\"})"
    }
   ]
  },
  {
   "title": "Excess Blocks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(hadoop_hdfs_namenode_fsnamesystem_blocks{cluster=~\"$cluster\", type=\"Excess\"})"
    }
   ]
  },
  {
   "title": "PendingDeletion Blocks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(hadoop_hdfs_namenode_fsnamesystem_blocks{cluster=~\"$cluster\", type=\"PendingDeletion\"})"
    }
   ]
  },
  { "title": "NameNode Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Sumary",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_fsstate{cluster=~\"$cluster\", host=~\"$namenode\"}"
    },
    {
     "expr": "hadoop_hdfs_namenode_hastate{cluster=~\"$cluster\", host=~\"$namenode\"}"
    },
    {
     "expr": "max(hadoop_hdfs_namenode_operatingsystem{cluster=~\"$cluster\", type=\"ProcessCpuLoad\",host=~\"$namenode\"}) by (host)"
    },
    {
     "expr": "max(hadoop_hdfs_namenode_operatingsystem{cluster=~\"$cluster\", type=\"SystemCpuLoad\",host=~\"$namenode\"}) by (host)"
    },
    {
     "expr": "max(hadoop_hdfs_namenode_operatingsystem{cluster=~\"$cluster\", type=\"SystemLoadAverage\",host=~\"$namenode\"}) by (host)"
    },
    {
     "expr": "max(hadoop_hdfs_namenode_jvmmetrics_mem{cluster=~\"$cluster\", type=\"HeapMaxM\", host=~\"$namenode\"}) by (host)"
    },
    {
     "expr": "sum(hadoop_hdfs_namenode_rpcactivity{cluster=~\"$cluster\", type=\"NumOpenConnections\", host=~\"$namenode\"}) by (host)"
    },
    {
     "expr": "hadoop_hdfs_namenode_fsnamesystem{cluster=~\"$cluster\", type=\"LastCheckpointTime\"}"
    },
    {
     "expr": "hadoop_hdfs_namenode_fsnamesystem{cluster=~\"$cluster\", type=\"LastWrittenTransactionId\"}"
    }
   ]
  },
  {
   "title": "System Cpu Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_operatingsystem{cluster=~\"$cluster\", type=\"SystemCpuLoad\",host=~\"$namenode\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "System LoadAvg",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_operatingsystem{cluster=~\"$cluster\", type=\"SystemLoadAverage\",host=~\"$namenode\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_jvmmetrics_mem{cluster=~\"$cluster\", type=\"HeapUsedM\", host=~\"$namenode\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Process Cpu Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_operatingsystem{cluster=~\"$cluster\", type=\"ProcessCpuLoad\",host=~\"$namenode\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Pending Deletion Blocks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_fsnamesystemstate_blocks{cluster=~\"$cluster\", type=\"PendingDeletion\",host=~\"$namenode\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(hadoop_hdfs_namenode_jvmmetrics_gc{cluster=~\"$cluster\", type=\"TimeMillis\", host=~\"$namenode\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(hadoop_hdfs_namenode_jvmmetrics_gc{cluster=~\"$cluster\", type=\"Count\", host=~\"$namenode\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Pending Replication Blocks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_fsnamesystemstate_blocks{cluster=~\"$cluster\", type=\"PendingReplication\",host=~\"$namenode\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Pending Reconstruction Blocks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_fsnamesystemstate_blocks{cluster=~\"$cluster\", type=\"PendingReconstruction\",host=~\"$namenode\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "JournalNode Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Sumary",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "max(hadoop_hdfs_namenode_operatingsystem{cluster=~\"$cluster\", type=\"ProcessCpuLoad\",host=~\"$journalnode\"}) by (host)"
    },
    {
     "expr": "max(hadoop_hdfs_namenode_operatingsystem{cluster=~\"$cluster\", type=\"SystemCpuLoad\",host=~\"$journalnode\"}) by (host)"
    },
    {
     "expr": "max(hadoop_hdfs_namenode_operatingsystem{cluster=~\"$cluster\", type=\"SystemLoadAverage\",host=~\"$journalnode\"}) by (host)"
    },
    {
     "expr": "max(hadoop_hdfs_journalnode_jvmmetrics_mem{cluster=~\"$cluster\", type=\"HeapMaxM\", host=~\"$journalnode\"}) by (host)"
    },
    {
     "expr": "max(hadoop_hdfs_journalnode_metrics{cluster=~\"$cluster\", type=\"LastJournalTimestamp\", host=~\"$journalnode\"}) by (host)"
    },
    {
     "expr": "max(hadoop_hdfs_journalnode_metrics{cluster=~\"$cluster\", type=\"LastWrittenTxId\", host=~\"$journalnode\"}) by (host)"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "hadoop_hdfs_journalnode_jvmmetrics_mem{cluster=~\"$cluster\", type=\"HeapUsedM\", host=~\"$journalnode\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "System CpuLoad",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hadoop_hdfs_journalnode_operatingsystem{cluster=~\"$cluster\", type=\"SystemCpuLoad\",host=~\"$journalnode\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "System LoadAvg",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hadoop_hdfs_journalnode_operatingsystem{cluster=~\"$cluster\", type=\"SystemLoadAverage\",host=~\"$journalnode\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(hadoop_hdfs_journalnode_jvmmetrics_gc{cluster=~\"$cluster\", type=\"Count\", host=~\"$journalnode\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(hadoop_hdfs_journalnode_jvmmetrics_gc{cluster=~\"$cluster\", type=\"TimeMillis\", host=~\"$journalnode\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Process Cpu Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hadoop_hdfs_journalnode_operatingsystem{cluster=~\"$cluster\", type=\"ProcessCpuLoad\",host=~\"$journalnode\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Syncs60s Ops",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hadoop_hdfs_journalnode_syncs60s_numops{cluster=~\"$cluster\",host=~\"$journalnode\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Syncs60s 95th Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "hadoop_hdfs_journalnode_syncs60s_latency_micros{cluster=~\"$cluster\",host=~\"$journalnode\", percentile=\"95th\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Syncs60s 99th Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "hadoop_hdfs_journalnode_syncs60s_latency_micros{cluster=~\"$cluster\",host=~\"$journalnode\", percentile=\"99th\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "DataNode Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Sumary",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(hadoop_hdfs_datanode_operatingsystem{cluster=~\"$cluster\", type=\"ProcessCpuLoad\",host=~\"$datanode\"}) by (host)"
    },
    {
     "expr": "max(hadoop_hdfs_datanode_operatingsystem{cluster=~\"$cluster\", type=\"SystemCpuLoad\",host=~\"$datanode\"}) by (host)"
    },
    {
     "expr": "max(hadoop_hdfs_datanode_operatingsystem{cluster=~\"$cluster\", type=\"SystemLoadAverage\",host=~\"$datanode\"}) by (host)"
    },
    {
     "expr": "max(hadoop_hdfs_datanode_fsdatasetstate{cluster=~\"$cluster\", type=~\"Capacity\", host=~\"$datanode\"}) by (host)"
    },
    {
     "expr": "max(hadoop_hdfs_datanode_fsdatasetstate{cluster=~\"$cluster\", type=~\"Remaining\", host=~\"$datanode\"}) by (host)"
    },
    {
     "expr": "max(hadoop_hdfs_datanode_jvmmetrics_mem{cluster=~\"$cluster\", type=\"HeapMaxM\", host=~\"$datanode\"}) by (host)"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "hadoop_hdfs_datanode_jvmmetrics_mem{cluster=~\"$cluster\", type=\"HeapUsedM\", host=~\"$datanode\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Process Cpu Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hadoop_hdfs_datanode_operatingsystem{cluster=~\"$cluster\", type=\"ProcessCpuLoad\",host=~\"$datanode\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "System Cpu Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hadoop_hdfs_datanode_operatingsystem{cluster=~\"$cluster\", type=\"SystemCpuLoad\",host=~\"$datanode\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(hadoop_hdfs_datanode_jvmmetrics_gc{cluster=~\"$cluster\", type=\"Count\", host=~\"$datanode\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(hadoop_hdfs_datanode_jvmmetrics_gc{cluster=~\"$cluster\", type=\"TimeMillis\", host=~\"$datanode\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Flush Ops",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(hadoop_hdfs_datanode_datanodeactivity{cluster=~\"$cluster\", type=\"FlushNanosNumOps\",host=~\"$datanode\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Flush  AvgTime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "hadoop_hdfs_datanode_datanodeactivity{cluster=~\"$cluster\", type=\"FlushNanosAvgTime\",host=~\"$datanode\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Heartbeats Ops",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(hadoop_hdfs_datanode_datanodeactivity{cluster=~\"$cluster\", type=\"HeartbeatsNumOps\",host=~\"$datanode\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Heartbeats AvgTime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "hadoop_hdfs_datanode_datanodeactivity{cluster=~\"$cluster\", type=\"HeartbeatsAvgTime\",host=~\"$datanode\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Read Blocks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(hadoop_hdfs_datanode_datanodeactivity{cluster=~\"$cluster\", type=\"BlocksRead\",host=~\"$datanode\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Written Blocks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(hadoop_hdfs_datanode_datanodeactivity{cluster=~\"$cluster\", type=\"BlocksWritten\",host=~\"$datanode\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Removed Blocks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(hadoop_hdfs_datanode_datanodeactivity{cluster=~\"$cluster\", type=\"BlocksRemoved\",host=~\"$datanode\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Verified Blocks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(hadoop_hdfs_datanode_datanodeactivity{cluster=~\"$cluster\", type=\"BlocksVerified\",host=~\"$datanode\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Read Ops",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(hadoop_hdfs_datanode_datanodeactivity{cluster=~\"$cluster\", type=\"ReadBlockOpNumOps\",host=~\"$datanode\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Read AvgTime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "hadoop_hdfs_datanode_datanodeactivity{cluster=~\"$cluster\", type=\"ReadBlockOpAvgTime\",host=~\"$datanode\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Write Ops",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(hadoop_hdfs_datanode_datanodeactivity{cluster=~\"$cluster\", type=\"WriteBlockOpNumOps\",host=~\"$datanode\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Write AvgTime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "hadoop_hdfs_datanode_datanodeactivity{cluster=~\"$cluster\", type=\"WriteBlockOpAvgTime\",host=~\"$datanode\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Local Read Ops",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(hadoop_hdfs_datanode_datanodeactivity{cluster=~\"$cluster\", type=\"ReadsFromLocalClient\",host=~\"$datanode\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Local Write Ops",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(hadoop_hdfs_datanode_datanodeactivity{cluster=~\"$cluster\", type=\"WritesFromLocalClient\",host=~\"$datanode\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Remote Read Ops",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(hadoop_hdfs_datanode_datanodeactivity{cluster=~\"$cluster\", type=\"ReadsFromRemoteClient\",host=~\"$datanode\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Remote Write Ops ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(hadoop_hdfs_datanode_datanodeactivity{cluster=~\"$cluster\", type=\"WritesFromRemoteClient\",host=~\"$datanode\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Remote Read  Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(hadoop_hdfs_datanode_datanodeactivity{cluster=~\"$cluster\", type=\"RemoteBytesRead\",host=~\"$datanode\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Remote Write Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(hadoop_hdfs_datanode_datanodeactivity{cluster=~\"$cluster\", type=\"RemoteBytesWritten\",host=~\"$datanode\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Volume Failures",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(hadoop_hdfs_datanode_datanodeactivity{cluster=~\"$cluster\", type=\"VolumeFailures\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(hadoop_hdfs_datanode_datanodeactivity{cluster=~\"$cluster\", type=\"DatanodeNetworkErrors\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}