{
 "title": "YARN Overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(hadoop_yarn_resourcemanager_state, cluster)"
    }
   },
   {
    "name": "resourcemanager",
    "label": "resourcemanager",
    "query": {
     "query": "label_values(hadoop_yarn_resourcemanager_state{cluster=~\"$cluster\"}, host)"
    }
   },
   {
    "name": "nodemanager",
    "label": "nodemanager",
    "query": {
     "query": "label_values(hadoop_yarn_nodemanager_operatingsystem{cluster=~\"$cluster\"}, host)"
    }
   },
   {
    "name": "queue0",
    "label": "queue0",
    "query": {
     "query": "label_values(hadoop_yarn_resourcemanager_queuemetrics{cluster=~\"$cluster\"}, queue0)"
    }
   },
   {
    "name": "queue1",
    "label": "queue1",
    "query": {
     "query": "label_values(hadoop_yarn_resourcemanager_queuemetrics{cluster=~\"$cluster\", queue0=~\"$queue0\"}, queue1)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Vcores",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(hadoop_yarn_resourcemanager_queuemetrics_vcores{cluster=~\"$cluster\", queue0=~\"$queue0\", type=~\"Available|Allocated\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(hadoop_yarn_resourcemanager_queuemetrics_mb{cluster=~\"$cluster\", queue0=~\"$queue0\", type=~\"Allocated|Available\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Running Apps",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(hadoop_yarn_resourcemanager_queuemetrics_apps{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"Running\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Pending Apps",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(hadoop_yarn_resourcemanager_queuemetrics_apps{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"Pending\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Allocated Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(hadoop_yarn_resourcemanager_queuemetrics_containers{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"Allocated\"})"
    }
   ]
  },
  {
   "title": "Pending Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(hadoop_yarn_resourcemanager_queuemetrics_containers{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Killed Apps",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(hadoop_yarn_resourcemanager_queuemetrics_apps{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"Killed\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Failed Apps",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(hadoop_yarn_resourcemanager_queuemetrics_apps{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"Failed\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "App's Success Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(hadoop_yarn_resourcemanager_queuemetrics_apps{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"Completed\"}) / max(hadoop_yarn_resourcemanager_queuemetrics_apps{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"Submitted\"})"
    }
   ]
  },
  {
   "title": "Reserved Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(hadoop_yarn_resourcemanager_queuemetrics_containers{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"Reserved\"})"
    }
   ]
  },
  {
   "title": "ResourceManagers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(hadoop_yarn_resourcemanager_state{cluster=~\"$cluster\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Active NMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(hadoop_yarn_resourcemanager_clustermetrics_num_nms{cluster=~\"$cluster\", type=\"Active\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Unhealthy NMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(hadoop_yarn_resourcemanager_clustermetrics_num_nms{cluster=~\"$cluster\", type=\"Unhealthy\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Decommissioned NMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(hadoop_yarn_resourcemanager_clustermetrics_num_nms{cluster=~\"$cluster\", type=\"Decommissioned\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Decommissioning NMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(hadoop_yarn_resourcemanager_clustermetrics_num_nms{cluster=~\"$cluster\", type=\"Decommissioning\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(hadoop_yarn_resourcemanager_queuemetrics{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"UsedCapacity\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Max Capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(hadoop_yarn_resourcemanager_queuemetrics{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"MaxCapacity\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Guaranteed Capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(hadoop_yarn_resourcemanager_queuemetrics{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"GuaranteedCapacity\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "ResourceManager Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Sumary",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "max(hadoop_yarn_resourcemanager_state{cluster=~\"$cluster\", host=~\"$resourcemanager\"}) by (host)"
    },
    {
     "expr": "max(hadoop_yarn_resourcemanager_operatingsystem{cluster=~\"$cluster\", type=\"ProcessCpuLoad\",host=~\"$resourcemanager\"}) by (host)"
    },
    {
     "expr": "max(hadoop_yarn_resourcemanager_operatingsystem{cluster=~\"$cluster\", type=\"SystemCpuLoad\",host=~\"$resourcemanager\"}) by (host)"
    },
    {
     "expr": "max(hadoop_yarn_resourcemanager_operatingsystem{cluster=~\"$cluster\", type=\"SystemLoadAverage\",host=~\"$resourcemanager\"}) by (host)"
    },
    {
     "expr": "max(hadoop_yarn_resourcemanager_operatingsystem{cluster=~\"$cluster\", type=\"AvailableProcessors\",host=~\"$resourcemanager\"}) by (host)"
    },
    {
     "expr": "max(hadoop_yarn_resourcemanager_operatingsystem{cluster=~\"$cluster\", type=\"TotalPhysicalMemorySize\",host=~\"$resourcemanager\"}) by (host)"
    },
    {
     "expr": "max(hadoop_yarn_resourcemanager_operatingsystem{cluster=~\"$cluster\", type=\"TotalSwapSpaceSize\",host=~\"$resourcemanager\"}) by (host)"
    },
    {
     "expr": "hadoop_yarn_resourcemanager_jvmmetrics_mem{cluster=~\"$cluster\", type=\"MaxM\"}"
    },
    {
     "expr": "hadoop_yarn_resourcemanager_jvmmetrics_mem{cluster=~\"$cluster\", type=\"HeapMaxM\"}"
    }
   ]
  },
  {
   "title": "Process CpuLoad",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hadoop_yarn_resourcemanager_operatingsystem{cluster=~\"$cluster\", host=~\"$resourcemanager\", type=\"ProcessCpuLoad\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "System CpuLoad",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hadoop_yarn_resourcemanager_operatingsystem{cluster=~\"$cluster\", host=~\"$resourcemanager\", type=\"SystemCpuLoad\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "hadoop_yarn_resourcemanager_jvmmetrics_mem{cluster=~\"$cluster\", host=~\"$resourcemanager\", type=\"HeapUsedM\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "NonHeap Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "hadoop_yarn_resourcemanager_jvmmetrics_mem{cluster=~\"$cluster\", host=~\"$resourcemanager\", type=\"NonHeapUsedM\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "AM Launch Delay",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "hadoop_yarn_resourcemanager_clustermetrics_avgtime{cluster=~\"$cluster\", host=~\"$resourcemanager\", type=\"AMLaunchDelay\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "AM Container Allocation Delay",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "hadoop_yarn_resourcemanager_clustermetrics_avgtime{cluster=~\"$cluster\", host=~\"$resourcemanager\", type=\"AMContainerAllocationDelay\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(hadoop_yarn_resourcemanager_jvmmetrics_gc{cluster=~\"$cluster\", host=~\"$resourcemanager\", type=\"Count\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(hadoop_yarn_resourcemanager_jvmmetrics_gc{cluster=~\"$cluster\", host=~\"$resourcemanager\", type=\"TimeMillis\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "AM Register Delay",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "hadoop_yarn_resourcemanager_clustermetrics_avgtime{cluster=~\"$cluster\", host=~\"$resourcemanager\", type=\"AMRegisterDelay\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Submitted Apps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(hadoop_yarn_resourcemanager_queuemetrics_apps{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"Submitted\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Running Apps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hadoop_yarn_resourcemanager_queuemetrics_apps{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"Running\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Resource Queues Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true
  },
  {
   "title": "Allocated Vcore",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_join(max(hadoop_yarn_resourcemanager_queuemetrics_vcores{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"MaxCapacity\"}) by (queue0, queue1), \"queue_id\", \".\", \"queue0\", \"queue1\")"
    },
    {
     "expr": "label_join(max(hadoop_yarn_resourcemanager_queuemetrics_vcores{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"Guaranteed\"}) by (queue0, queue1), \"queue_id\", \".\", \"queue0\", \"queue1\")"
    },
    {
     "expr": "label_join(max(hadoop_yarn_resourcemanager_queuemetrics_vcores{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"AMResourceLimit\"}) by (queue0, queue1), \"queue_id\", \".\", \"queue0\", \"queue1\")"
    },
    {
     "expr": "label_join(max(hadoop_yarn_resourcemanager_queuemetrics_mb{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"MaxCapacity\"}) by (queue0, queue1), \"queue_id\", \".\", \"queue0\", \"queue1\")"
    },
    {
     "expr": "label_join(max(hadoop_yarn_resourcemanager_queuemetrics_mb{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"Guaranteed\"}) by (queue0, queue1), \"queue_id\", \".\", \"queue0\", \"queue1\")"
    },
    {
     "expr": "label_join(max(hadoop_yarn_resourcemanager_queuemetrics_mb{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"AMResourceLimit\"}) by (queue0, queue1), \"queue_id\", \".\", \"queue0\", \"queue1\")"
    }
   ]
  },
  {
   "title": "Completed Applications",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(increase(hadoop_yarn_resourcemanager_queuemetrics_apps{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"Completed\"}[1m])) by (queue0, queue1)",
     "legendFormat": "{{queue0}}.{{queue1}}"
    }
   ]
  },
  {
   "title": "Failed Applications",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(increase(hadoop_yarn_resourcemanager_queuemetrics_apps{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"Failed\"}[1m])) by (queue0, queue1)",
     "legendFormat": "{{queue0}}.{{queue1}}"
    }
   ]
  },
  {
   "title": "Pending Applications",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(increase(hadoop_yarn_resourcemanager_queuemetrics_apps{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"Pending\"}[1m])) by (queue0, queue1)",
     "legendFormat": "{{queue0}}.{{queue1}}"
    }
   ]
  },
  {
   "title": "Killed Applications",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(increase(hadoop_yarn_resourcemanager_queuemetrics_apps{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"Killed\"}[1m])) by (queue0, queue1)",
     "legendFormat": "{{queue0}}.{{queue1}}"
    }
   ]
  },
  {
   "title": "Running Applications",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(increase(hadoop_yarn_resourcemanager_queuemetrics_apps{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"Running\"}[1m])) by (queue0, queue1)",
     "legendFormat": "{{queue0}}.{{queue1}}"
    }
   ]
  },
  {
   "title": "Submitted Applications",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(increase(hadoop_yarn_resourcemanager_queuemetrics_apps{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"Submitted\"}[1m])) by (queue0, queue1)",
     "legendFormat": "{{queue0}}.{{queue1}}"
    }
   ]
  },
  {
   "title": "Allocated Containers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(increase(hadoop_yarn_resourcemanager_queuemetrics_containers{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"Allocated\"}[1m])) by (queue0, queue1)",
     "legendFormat": "{{queue0}}.{{queue1}}"
    }
   ]
  },
  {
   "title": "Pending Containers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(increase(hadoop_yarn_resourcemanager_queuemetrics_containers{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"Pending\"}[1m])) by (queue0, queue1)",
     "legendFormat": "{{queue0}}.{{queue1}}"
    }
   ]
  },
  {
   "title": "Reserved Containers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(increase(hadoop_yarn_resourcemanager_queuemetrics_containers{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"Reserved\"}[1m])) by (queue0, queue1)",
     "legendFormat": "{{queue0}}.{{queue1}}"
    }
   ]
  },
  {
   "title": "Allocated Vcore",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(hadoop_yarn_resourcemanager_queuemetrics_vcores{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"Allocated\"}) by (queue0, queue1)",
     "legendFormat": "{{queue0}}.{{queue1}}"
    }
   ]
  },
  {
   "title": "Available Vcore",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(hadoop_yarn_resourcemanager_queuemetrics_vcores{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"Available\"}) by (queue0, queue1)",
     "legendFormat": "{{queue0}}.{{queue1}}"
    }
   ]
  },
  {
   "title": "Pending Vcore",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(hadoop_yarn_resourcemanager_queuemetrics_vcores{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"Pending\"}) by (queue0, queue1)",
     "legendFormat": "{{queue0}}.{{queue1}}"
    }
   ]
  },
  {
   "title": "Reserved Vcore",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(hadoop_yarn_resourcemanager_queuemetrics_vcores{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"Reserved\"}) by (queue0, queue1)",
     "legendFormat": "{{queue0}}.{{queue1}}"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "max(hadoop_yarn_resourcemanager_queuemetrics_mb{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"Allocated\"}) by (queue0, queue1)",
     "legendFormat": "{{queue0}}.{{queue1}}"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "max(hadoop_yarn_resourcemanager_queuemetrics_mb{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"Available\"}) by (queue0, queue1)",
     "legendFormat": "{{queue0}}.{{queue1}}"
    }
   ]
  },
  {
   "title": "Pending Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "max(hadoop_yarn_resourcemanager_queuemetrics_mb{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"Pending\"}) by (queue0, queue1)",
     "legendFormat": "{{queue0}}.{{queue1}}"
    }
   ]
  },
  {
   "title": "Reversed Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "max(hadoop_yarn_resourcemanager_queuemetrics_mb{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"Reserved\"}) by (queue0, queue1)",
     "legendFormat": "{{queue0}}.{{queue1}}"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(hadoop_yarn_resourcemanager_queuemetrics{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"UsedCapacity\"}) by (queue0, queue1)",
     "legendFormat": "{{queue0}}.{{queue1}}"
    }
   ]
  },
  {
   "title": "Max Capacity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(hadoop_yarn_resourcemanager_queuemetrics{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"MaxCapacity\"}) by (queue0, queue1)",
     "legendFormat": "{{queue0}}.{{queue1}}"
    }
   ]
  },
  {
   "title": "Max Absolute Capacity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(hadoop_yarn_resourcemanager_queuemetrics{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"MaxAbsoluteCapacity\"}) by (queue0, queue1)",
     "legendFormat": "{{queue0}}.{{queue1}}"
    }
   ]
  },
  {
   "title": "Guaranteed Capacity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(hadoop_yarn_resourcemanager_queuemetrics{cluster=~\"$cluster\", queue0=~\"$queue0\", queue1=~\"$queue1\", type=\"GuaranteedCapacity\"}) by (queue0, queue1)",
     "legendFormat": "{{queue0}}.{{queue1}}"
    }
   ]
  },
  {
   "title": "NodeManager Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true
  },
  {
   "title": "Sumary",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "max(hadoop_yarn_nodemanager_operatingsystem{cluster=~\"$cluster\", type=\"ProcessCpuLoad\",host=~\"$nodemanager\"}) by (host)"
    },
    {
     "expr": "max(hadoop_yarn_nodemanager_operatingsystem{cluster=~\"$cluster\", type=\"SystemCpuLoad\",host=~\"$nodemanager\"}) by (host)"
    },
    {
     "expr": "max(hadoop_yarn_nodemanager_operatingsystem{cluster=~\"$cluster\", type=\"SystemLoadAverage\",host=~\"$nodemanager\"}) by (host)"
    },
    {
     "expr": "max(hadoop_yarn_nodemanager_operatingsystem{cluster=~\"$cluster\", type=\"AvailableProcessors\",host=~\"$nodemanager\"}) by (host)"
    },
    {
     "expr": "max(hadoop_yarn_nodemanager_operatingsystem{cluster=~\"$cluster\", type=\"TotalPhysicalMemorySize\",host=~\"$nodemanager\"}) by (host)"
    },
    {
     "expr": "max(hadoop_yarn_nodemanager_operatingsystem{cluster=~\"$cluster\", type=\"TotalSwapSpaceSize\",host=~\"$nodemanager\"}) by (host)"
    },
    {
     "expr": "max(hadoop_yarn_nodemanager_jvmmetrics_mem{cluster=~\"$cluster\", type=\"MaxM\",host=~\"$nodemanager\"}) by (host)"
    },
    {
     "expr": "max(hadoop_yarn_nodemanager_jvmmetrics_mem{cluster=~\"$cluster\", type=\"HeapMaxM\",host=~\"$nodemanager\"}) by (host)"
    }
   ]
  },
  {
   "title": "Process CpuLoad",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "hadoop_yarn_nodemanager_operatingsystem{cluster=~\"$cluster\", host=~\"$nodemanager\", type=\"ProcessCpuLoad\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "System CpuLoad",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "hadoop_yarn_nodemanager_operatingsystem{cluster=~\"$cluster\", host=~\"$nodemanager\", type=\"SystemCpuLoad\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "hadoop_yarn_nodemanager_jvmmetrics_mem{cluster=~\"$cluster\", host=~\"$nodemanager\", type=\"HeapUsedM\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "NonHeap Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "hadoop_yarn_nodemanager_jvmmetrics_mem{cluster=~\"$cluster\", host=~\"$nodemanager\", type=\"NonHeapUsedM\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Allocated Containers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hadoop_yarn_nodemanager_nodemanagermetrics{cluster=~\"$cluster\", host=~\"$nodemanager\", type=\"AllocatedContainers\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Running Applications",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hadoop_yarn_nodemanager_nodemanagermetrics{cluster=~\"$cluster\", host=~\"$nodemanager\", type=\"ApplicationsRunning\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(hadoop_yarn_nodemanager_jvmmetrics_gc{cluster=~\"$cluster\", host=~\"$nodemanager\", type=\"Count\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(hadoop_yarn_nodemanager_jvmmetrics_gc{cluster=~\"$cluster\", host=~\"$nodemanager\", type=\"TimeMillis\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Available VCores",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hadoop_yarn_nodemanager_nodemanagermetrics{cluster=~\"$cluster\", host=~\"$nodemanager\", type=\"AvailableVCores\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Allocated VCores",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hadoop_yarn_nodemanager_nodemanagermetrics{cluster=~\"$cluster\", host=~\"$nodemanager\", type=\"AllocatedVCores\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "ContainerLaunchDuration NumOps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hadoop_yarn_nodemanager_nodemanagermetrics{cluster=~\"$cluster\", host=~\"$nodemanager\", type=\"ContainerLaunchDurationNumOps\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "ContainerLaunchDuration AvgTime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "hadoop_yarn_nodemanager_nodemanagermetrics{cluster=~\"$cluster\", host=~\"$nodemanager\", type=\"ContainerLaunchDurationAvgTime\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Container Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "hadoop_yarn_nodemanager_nodemanagermetrics{cluster=~\"$cluster\", host=~\"$nodemanager\", type=\"ContainerUsedMemGB\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Container Used Virtual Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "hadoop_yarn_nodemanager_nodemanagermetrics{cluster=~\"$cluster\", host=~\"$nodemanager\", type=\"ContainerUsedVMemGB\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "hadoop_yarn_nodemanager_nodemanagermetrics{cluster=~\"$cluster\", host=~\"$nodemanager\", type=\"AllocatedGB\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "hadoop_yarn_nodemanager_nodemanagermetrics{cluster=~\"$cluster\", host=~\"$nodemanager\", type=\"AvailableGB\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Node Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "hadoop_yarn_nodemanager_nodemanagermetrics{cluster=~\"$cluster\", host=~\"$nodemanager\", type=\"NodeUsedMemGB\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Node Used Virtual Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "hadoop_yarn_nodemanager_nodemanagermetrics{cluster=~\"$cluster\", host=~\"$nodemanager\", type=\"NodeUsedVMemGB\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Spark Shuffle Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 } },
  {
   "title": "Registered Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hadoop_yarn_nodemanager_sparkshuffleservice{cluster=~\"$cluster\", host=~\"$nodemanager\", type=\"numRegisteredConnections\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hadoop_yarn_nodemanager_sparkshuffleservice{cluster=~\"$cluster\", host=~\"$nodemanager\", type=\"numActiveConnections\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Register Executor Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "hadoop_yarn_nodemanager_sparkshuffleservice_registerexecutorrequestlatencymillis{cluster=~\"$cluster\", host=~\"$nodemanager\", type=\"mean\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Open Block Request latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "hadoop_yarn_nodemanager_sparkshuffleservice_openblockrequestlatencymillis{cluster=~\"$cluster\", host=~\"$nodemanager\", type=\"mean\"}",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}